book_catalogue/urls.py
from django.contrib import admin
from django.urls import path, include
from book_catalogue import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('users.urls')),
    path('', include('book_swap.urls')),
    path('', include('book_request.urls')),
    path('', include('user_profile.urls')),
    path('', include('catalog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book_request/urls.py
from django.urls import path
from book_request.views import request_book_by_ajax, get_requested_book_json, view_all_requests, approve_request, reject_request, request_book_mobile

app_name = 'book_request'

urlpatterns = [
    path('request-book/', request_book_by_ajax, name='request_book'),
    path('get-requested-book/', get_requested_book_json, name='get_requested_book'),
    path('requests/', view_all_requests, name='view_all_requests'),
    path('requests/approve/<int:request_id>', approve_request, name='approve_request'),
    path('requests/reject/<int:request_id>', reject_request, name='reject_request'),
    path('request-book-mobile/', request_book_by_ajax, name='request_book_mobile'),
]

main/urls.py
from django.urls import path
from main.views import get_books, get_books_by_genre, get_books_by_name, show_main

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('get-books/', get_books, name='get_books'),
    path('get-books-by-name/<str:name>', get_books_by_name, name='get_books_by_name'),
    path('get-books-by-genre/<str:name>', get_books_by_genre, name='get_books_by_genre'),
]

book_request/models.py
from django.db import models
from django.conf import settings
from main.models import Book

class RequestBook(models.Model):
    PENDING = 'PENDING'
    APPROVED = 'APPROVED'
    REJECTED = 'REJECTED'

    STATUS_CHOICES = [
        (PENDING, 'Pending'),
        (APPROVED, 'Approved'),
        (REJECTED, 'Rejected'),
    ]
    
    name = models.CharField(max_length=512)
    author = models.CharField(max_length=512)
    original_language = models.CharField(max_length=256)
    year_published = models.IntegerField()
    sales = models.IntegerField()
    genre = models.CharField(max_length=256)
    cover_image = models.ImageField(null=True, upload_to="input/cover")
    request_date_added = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    request_status = models.CharField(max_length=8, choices=STATUS_CHOICES, default=PENDING)

book_request/forms.py
from django.forms import ModelForm
from .models import RequestBook

class RequestBookForm(ModelForm):
    class Meta:
        model = RequestBook
        fields = ["name", "author", "original_language", "year_published", "sales", "genre", "cover_image"]

book_request/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.admin.views.decorators import staff_member_required
from django.http import JsonResponse, HttpResponse, HttpResponseForbidden, HttpResponseNotFound
from django.core import serializers
from .models import Book, RequestBook
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from book_request.forms import RequestBookForm
from main.models import Book
import json

@csrf_exempt
def request_book_by_ajax(request):
    if request.method == 'POST':
        form = RequestBookForm(request.POST, request.FILES)
        if form.is_valid():
            user_request = form.save(commit=False)
            user_request.request_status = 'PENDING'
            user_request.user = request.user
            user_request.save()
            return JsonResponse({'status': True, 'message': 'Request Added Successfully'})
        else:
            return JsonResponse({'status': False, 'errors': form.errors, 'message': 'Request Failed'})
    else:
        form = RequestBookForm()
        return render(request, 'book_request_by_ajax.html', {'form': form})

# @csrf_exempt
# def request_book_by_ajax(request):
#     if request.method == 'POST':
#         name = request.POST.get("name")
#         author = request.POST.get("author")
#         original_language = request.POST.get("original_language")
#         year_published = request.POST.get("year_published")
#         sales = request.POST.get("sales")
#         genre = request.POST.get("genre")
#         cover_image = request.POST.get("cover_image")
#         user = request.user
#         request_status = "PENDING"
#         new_book_request = RequestBook(name=name, author=author, original_language=original_language,
#         year_published=year_published, sales=sales, genre=genre, cover_image=cover_image, user=user, request_status=request_status)
#         new_book_request.save()
#         return HttpResponse(b"CREATED REQUEST", status=201)
#     return HttpResponseNotFound()

@csrf_exempt
def request_book_mobile(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        new_book_request = RequestBook.objects.create(
            user = request.user,
            name = data['name'],
            author = data['author'],
            original_language = data['original_language'],
            year_published = int(data['year_published']),
            sales = int(data['sales']),
            genre = data['genre'],
            cover_image = data['cover_image']
        )
        new_book_request.save()
        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)
    
@login_required
def get_requested_book_json(request):
    data = RequestBook.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@staff_member_required
def view_all_requests(request):
    all_requests = RequestBook.objects.all()
    return render(request, 'all_book_requests.html', {'requests': all_requests})

@csrf_exempt
def approve_request(request, request_id):

    if not request.user.is_superuser:
        return HttpResponseForbidden("You don't have permission to perform this action.")
    
    req = get_object_or_404(RequestBook, pk=request_id)
    req.request_status = RequestBook.APPROVED
    req.save()

    if request.method == 'POST':
        data = json.loads(request.body)
        
        new_book = Book.objects.create(
            name = data["name"],
            author = data["author"],
            original_language = data["original_language"],
            year_published = data["year_published"],
            sales = data["sales"],
            genre = data["genre"],
            cover_image = data["cover_image"]
        )
        new_book.save()

        return JsonResponse({"status": "success"}, status = 200)
    else:
        return JsonResponse({"status": "failed"}, status = 401)

def load_books():
    with open('main:fixtures/initial_books.json', 'r') as file:
        return json.load(file)
        
@csrf_exempt
def reject_request(request, request_id):
    if not request.user.is_superuser:
        return HttpResponseForbidden("You don't have permission to perform this action.")
    
    req = get_object_or_404(RequestBook, pk=request_id)
    req.request_status = RequestBook.REJECTED
    req.save()
    return redirect('view_all_requests') 

book_request/templates/all_book_requests.html
<!-- all_requests.html -->
<!DOCTYPE html>
<html>
<head>
    <title>All Requests</title>
</head>
<body>
    <h1>All Requests</h1>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Author</th>
                <th>Status</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for request in requests %}
                <tr>
                    <td>{{ request.name }}</td>
                    <td>{{ request.author }}</td>
                    <td>{{ request.get_request_status_display }}</td>
                    <td>
                        <form method="POST" action="{% url 'approve_request' request.id %}">
                            {% csrf_token %}
                            <input type="submit" value="Approve">
                        </form>
                        <form method="POST" action="{% url 'reject_request' request.id %}">
                            {% csrf_token %}
                            <input type="submit" value="Reject">
                        </form>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

book_request/templates/book_request_by_ajax.html
{% extends 'base.html' %}

{% block content %}
<div>
    <!-- Header -->
    {% include 'header.html' %}

    <!-- Modal -->
    <dialog class="modal rounded-lg" id="modal">
        <div id="form_div" class="w-full h-auto mx-auto rounded-b-lg bg-white flex flex-col md:flex-row justify-center shadow-2xl" style="display:none;">
            <div class="flex flex-col w-full h-full min-h-screen items-center justify-center bg-gradient-to-r from-gray-100 to-blue-200">
                <div class="h-14 bg-gradient-to-r from-cyan-400 to-blue-700 flex flex-col lg:flex-row rounded-xl w-[300px] lg:w-[1400px] h-[600px] lg:h-[700px] bg-white shadow-2xl relative">            
            <!-- Form to submit the book request -->
            <form id="form" onsubmit="addBookRequest(); return false;" class="w-full max-w-lg" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="flex flex-wrap -mx-3 mb-6">
                    <div class="w-full px-3">
                        <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="id_name">
                            Book Name
                        </label>
                        <input class="appearance-none block w-full bg-gray-200 text-gray-700 border rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white" id="id_name" type="text" name="name" placeholder="Book Name" required>
                    </div>
                    <div class="w-full px-3">
                        <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="id_author">
                            Author
                        </label>
                        <input class="appearance-none block w-full bg-gray-200 text-gray-700 border rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white" id="id_author" type="text" name="author" placeholder="Author" required>
                    </div>
                    <div class="w-full px-3">
                        <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="id_original_language">
                            Original Language
                        </label>
                        <input class="appearance-none block w-full bg-gray-200 text-gray-700 border rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white" id="id_original_language" type="text" name="original_language" placeholder="Original Language" required>
                    </div>
                    <div class="w-full px-3">
                        <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="id_year_published">
                            Year Published
                        </label>
                        <input class="appearance-none block w-full bg-gray-200 text-gray-700 border rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white" id="id_year_published" type="number" name="year_published" placeholder="Year Published" required>
                    </div>
                    <div class="w-full px-3">
                        <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="id_sales">
                            Sales
                        </label>
                        <input class="appearance-none block w-full bg-gray-200 text-gray-700 border rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white" id="id_sales" type="number" name="sales" placeholder="Sales" required>
                    </div>
                    <div class="w-full px-3">
                        <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="id_genre">
                            Genre
                        </label>
                        <input class="appearance-none block w-full bg-gray-200 text-gray-700 border rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white" id="id_genre" type="text" name="genre" placeholder="Genre" required>
                    </div>
                    <div class="w-full px-3">
                        <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="id_cover_image">
                            Book Cover
                        </label>
                        <input class="appearance-none block w-full bg-gray-200 text-gray-700 border rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white" id="id_cover_image" type="file" name="cover_image" required>
                    </div>
                </div>
                <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded close-button" type="submit">Submit</button>
                <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded cancel-button" type="button">Cancel</button>
            </form>
        </div>
      </dialog>

    <!-- Container for showing book requests made by other users -->
    <div class="w-full md:w-500px rounded-lg mx-auto p-12 flex justify-center">
        <div class="w-full h-auto mx-auto bg-blue-400 items-center rounded-lg shadow-2xl flex flex-col">
            <h1 class="text-white font-bold p-2 text-3xl">Book Requests</h1>
            <div class="w-full h-auto mx-auto rounded-b-lg bg-white flex flex-col md:flex-row justify-center shadow-2xl">
                <!-- Table -->
                <table id="request_table"></table>
            </div>
            <div class="w-full h-auto mx-auto rounded-b-lg bg-white flex flex-col md:flex-row justify-center shadow-2xl">
                <!-- Button to show the form -->
                <button id="button_add" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded my-4 open-button">Add Book Request</button>
            </div>            
        </div>
    </div>
</div>
<script>
    function toggleDropdownUser() {
        const dropdownButton = document.getElementById("dropdown_user_button");
        const dropdownMenu = document.getElementById("dropdown_user_menu");
        
        dropdownMenu.classList.toggle('opacity-0');
        dropdownMenu.classList.toggle('scale-100');
        dropdownMenu.classList.toggle('scale-0');
    }

    function toggleDropdownGeneral() {
        const dropdownButton = document.getElementById("dropdown_general_button");
        const dropdownMenu = document.getElementById("dropdown_general_menu");

        dropdownMenu.classList.toggle('scale-100');
        dropdownMenu.classList.toggle('scale-0');
        dropdownMenu.classList.toggle('h-0');
    }

    function toggleFormDisplay() {
        const formDiv = document.getElementById("form_div");
        formDiv.style.display = "block";
    }

    document.getElementById("button_add").addEventListener("click", toggleFormDisplay);
    document.getElementById("button_add").onclick = () => {
        toggleFormDisplay();
    };

    async function getRequests(){
        return fetch("{% url 'book_request:get_requested_book' %}").then((res) => res.json())
    }

    async function refreshRequests(){
        document.getElementById("request_table").innerHTML = ""
        const requests = await getRequests()
        let htmlString = `<tr>
            <th>Requested Book</th>
            <th>Request Date</th>
            <th>Request Status</th>
        </tr>`
        requests.forEach((request) => {
            htmlString += `\n<tr>
            <td>${request.fields.name}</td>
            <td>${request.fields.request_date_added}</td>
            <td>${request.fields.request_status}</td>
        </tr>`
        })

        document.getElementById("request_table").innerHTML = htmlString
    }

    refreshRequests()

    function toggleFormDisplay() {
        const formDiv = document.getElementById("form_div");
        formDiv.style.display = "block";
    }

    async function addBookRequest() {
        const form = document.getElementById("form");
        const formData = new FormData(form);

        await fetch("{% url 'book_request:request_book' %}", {
            method: "POST",
            body: formData,
        });

        refreshRequests();
        form.reset();
    }

    document.getElementById("button_add").addEventListener("click", toggleFormDisplay);

    async function refreshItems() {
        document.getElementById("itemDeck").innerHTML = ""
        const books = await getItems()
        let htmlString = ""
        books.forEach((book) => {
            htmlString += `\n
            <button onclick=selectBook(${book.pk})>
                <div class="flex flex-row items-center rounded-xl border transition shadow-md hover:shadow-xl w-[350px] sm:w-[250px] lg:w-[350px] h-[200px] px-4 py-3 gap-3 cursor-pointer">
                    <img src='/media/${book.fields.cover_image}' class='w-[100px] rounded-lg drop-shadow-md'>
                    <div class="flex-col w-[250px] sm:w-[150px] lg:w-[250px]">
                        <div class="line-clamp-1 lg:line-clamp-2 font-semibold text-lg text-black">${book.fields.name}</div>
                        <div class="line-clamp-1 font-normal text-slate-400 text-sm">${book.fields.author}</div>
                        <div class="flex flex-row gap-2">
                            {% for i in n %}
                                {% if i < 3 %}
                                    <svg xmlns="http://www.w3.org/2000/svg" class="w-[16px] h-[16px] fill-yellow-400 bi bi-star-fill my-2" viewBox="0 0 16 16"> 
                                        <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/> 
                                    </svg>
                                {% else %}
                                    <svg xmlns="http://www.w3.org/2000/svg" class="w-[16px] h-[16px] fill-gray-300 opacity-50 bi bi-star-fill my-2" viewBox="0 0 16 16"> 
                                        <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/> 
                                    </svg>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </button>`.replaceAll('177013', book.pk)
            
        });
        
        document.getElementById("itemDeck").innerHTML = htmlString;

        const hiddenElements = document.querySelectorAll("#card-book");
        console.log(hiddenElements);
        hiddenElements.forEach((element) => booksCardObserver.observe(element));
    }

    refreshItems()
    
    const modal = document.querySelector("#modal");
    const openModal = document.querySelector(".open-button");
    const closeModal = document.querySelector(".close-button");

    openModal.addEventListener("click", () => {
    modal.showModal();
    });

    closeModal.addEventListener("click", () => {
    modal.close();
    });

    const addBookButton = document.getElementById("button_add");
    const formDiv = document.getElementById("form_div")

    function cancelForm(){
        formDiv.style.display = "none"
        addBookButton.disabled = false;
    }
    document.querySelector(".cancel-button").addEventListener("click", cancelForm);

    // Event listener for the "Add Book Request" button
    addBookButton.addEventListener("click", () => {
        formDiv.style.display = "block";
        addBookButton.disabled = true;
    });
</script>

{% endblock content %}