book_catalogue/urls.py
from django.contrib import admin
from django.urls import path, include
from book_catalogue import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('users.urls')),
    path('', include('book_swap.urls')),
    path('', include('book_request.urls')),
    path('', include('user_profile.urls')),
    path('', include('catalog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book_swap/urls.py
from django.urls import path
from book_swap.views import show_json, show_processed_book_swap, show_queue_book_swap
from book_swap.views import show_accepted_book_swap, accept_swap,get_processed_book_json, search_key
from book_swap.views import cancel_swap
from book_swap.views import create_swap_mobile, create_swap, show_create_swap
from book_swap.views import get_model_data, delete_all_swap
from book_swap.views import get_processed_book_json, get_waiting_accept_book_json, get_accepted_book_json, get_finished_book_json
from book_swap.views import cancel_swap_mobile, accept_swap_mobile, finish_swap_mobile
app_name = 'book_swap'

urlpatterns = [
    path('delete_all_swap/', delete_all_swap, name='delete_all_swap'),
    path('get_model_data/', get_model_data, name='get_model_data'),
    path('create_swap/', create_swap, name='create_swap'),
    path('create_swap_page/', show_create_swap, name='show_create_swap'),
    path('waiting_swap/', show_queue_book_swap, name='show_queue_book_swap'), 
    path('book_swap/', show_processed_book_swap, name='show_processed_book_swap'),
    path('accepted_swap/', show_accepted_book_swap, name='show_accepted_book_swap'), 
    path('book_swap/json/', show_json, name='show_json'),
    path('book_swap/search/', search_key, name='search_key'),
    path('accept_swap/', accept_swap, name='accept_swap'),
    path('cancel_swap/', cancel_swap, name='cancel_swap'),
    path('get_processed_book_json/', get_processed_book_json, name='get_processed_book_json'),
    path('get_waiting_accept_book_json/', get_waiting_accept_book_json, name='get_waiting_accept_book_json'),
    path('get_accepted_book_json/', get_accepted_book_json, name='get_accepted_book_json'),
    path('get_finished_book_json/', get_finished_book_json, name='get_finished_book_json'),
    path('create_swap_mobile/', create_swap_mobile, name='create_swap_mobile'),
    path('cancel_swap_mobile/', cancel_swap_mobile, name='cancel_swap_mobile'),
    path('accept_swap_mobile/', accept_swap_mobile, name='accept_swap_mobile'),
    path('finish_swap_mobile/', finish_swap_mobile, name='finish_swap_mobile'),
]

main/urls.py
from django.urls import path
from main.views import get_books, get_books_by_genre, get_books_by_name, show_main

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('get-books/', get_books, name='get_books'),
    path('get-books-by-name/<str:name>', get_books_by_name, name='get_books_by_name'),
    path('get-books-by-genre/<str:name>', get_books_by_genre, name='get_books_by_genre'),
]

users/urls.py
from django.urls import path

from users.views import login_user, login_user_mobile, logout_user, logout_user_mobile, register_user, register_user_mobile

app_name = 'users'

urlpatterns = [
    path('login/', login_user, name='login'),
    path('register/', register_user, name='register'),
    path('logout/', logout_user, name='logout'),
    path('login-mobile/', login_user_mobile, name='login-mobile'),
    path('register-mobile/', register_user_mobile, name='register-mobile'),
    path('logout-mobile/', logout_user_mobile, name='logout-mobile'),
]

book_swap/models.py
from django.db import models
from django.contrib.auth.models import User
from main.models import Book
# Create your models here.
class BookSwap(models.Model):
    from_user = models.CharField(max_length=100, default='')
    to_user = models.CharField(max_length=100, default='') 
    have_book = models.TextField(max_length=500, default='')
    want_book = models.TextField(max_length=500)
    from_message = models.TextField(max_length=500)
    to_message = models.TextField(max_length=500, default='')
    processed = models.BooleanField(default=False)
    swapped = models.BooleanField(default=False)

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Avg

class Book(models.Model):
    name = models.CharField(max_length=512)
    author = models.CharField(max_length=512)
    original_language = models.CharField(max_length=256)
    year_published = models.IntegerField()
    sales = models.IntegerField()
    genre = models.CharField(max_length=256)
    cover_image = models.ImageField(null=True, upload_to="input/cover")

    @property
    def calculate_average_rating(self):
        return Review.objects.filter(book=self).aggregate(avg_rating=Avg('rating'))['avg_rating']

class Review(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    review = models.TextField(max_length=512)
    rating = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)

book_swap/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseNotFound, JsonResponse  
from django.urls import reverse
from book_swap.models import BookSwap
from django.contrib.auth.decorators import login_required
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt
from main.models import Book
from django.db.models import Q
import json
from django.core.serializers import serialize

def get_model_data(request):
    data = serialize('json', Book.objects.all())
    return JsonResponse(data, safe=False)

def get_specified_book_json(request, id):
    data = serialize('json', Book.objects.filter(pk=id))
    return JsonResponse(data, safe=False)

def delete_all_swap(request):
    BookSwap.objects.all().delete()
    return HttpResponse('deleted')

# create Book Swap
@login_required(login_url='/login')
def create_swap(request):
    if request.method == 'POST':
        import json
        post_data = json.loads(request.body.decode("utf-8"))
        ownedbook = post_data.get('ownedbook')
        wantedbook = post_data.get('wantedbook')
        frommessage = post_data.get('message')
        #print(from_user, ownedbook, wantedbook, frommessage)
        new_product = BookSwap.objects.create(
            from_user = request.user.username,
            have_book = ownedbook,
            from_message = frommessage,
            want_book = wantedbook,
        )
        new_product.save()
        return HttpResponseRedirect(reverse('book_swap:show_processed_book_swap'))
    
    return HttpResponseNotFound()


def show_create_swap(request):
    list_all_book = Book.objects.all()  
    return render(request, 'create_swap_page.html', {'username':request.user.username, 
                                                'list_all_book':list_all_book,})

@login_required(login_url='/login')
def show_processed_book_swap(request):
    swaps= BookSwap.objects.filter(from_user=request.user).filter(swapped=False)
    context = {
        'username':request.user.username, 
        'swaps':swaps,
    }
    return render(request, 'processed_book_swap.html', context)

@login_required(login_url='/login')
def show_queue_book_swap(request):
    swaps= BookSwap.objects.exclude(from_user=request.user).filter(swapped=False)
    context = {
        'username' : request.user.username, 
        'swaps': swaps,
    }
    return render(request, 'waiting_swap.html', context)

def search_key_waiting(request):
    if request.method == 'POST':  
        search_query = request.POST['search_query']
        swaps = BookSwap.objects.filter(Q(name__contains=search_query)| Q(from_user__contains=search_query)).filter(from_user=request.user).filter(swapped=False)
        return render(request, 'waiting_swap.html', {'query':search_query, 'swaps':swaps})
    else:
        return render(request, 'waiting_swap.html',{})
    
def show_json(request):
    data = BookSwap.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@login_required(login_url='/login')
def show_accepted_book_swap(request):
    swaps= BookSwap.objects.all().filter(swapped=True).filter(from_user=request.user)
    context = {
        'username' : request.user.username, 
        'swaps': swaps,
    }
    return render(request, 'accepted_swap.html', context)

def accept_swap(request):
    if request.method == 'POST':
        swaps = BookSwap.objects.all().filter(processed=False)
        acceptedSwap = swaps.get(pk=request.POST.get('id'))
        acceptedSwap.processed = True
        acceptedSwap.to_user = request.user.username
        acceptedSwap.to_message = request.POST.get('message')
        acceptedSwap.save()
        return HttpResponseRedirect(reverse('book_swap:show_processed_book_swap'))

    
def search_key(request):
    if request.method == 'POST':  
        search_query = request.POST['search_query']
        swaps = BookSwap.objects.filter(Q(name__contains=search_query)| Q(user__contains=search_query)).filter(user=request.user).filter(swapped=False)
        context = {
            'username' : request.user.username, 
            'swaps': swaps,
        }
        return render(request, 'waiting_swap.html', context)
    else:
        swaps= BookSwap.objects.exclude(user=request.user).filter(swapped=False)
        context = {
            'username' : request.user.username, 
            'swaps': swaps,
        }
        return render(request, 'waiting_swap.html', context)
@csrf_exempt
def cancel_swap(request):
    if request.method == 'POST':
        swaps = BookSwap.objects.filter(from_user = request.user).filter(swapped=False)
        deletedSwaps = swaps.get(pk=request.POST.get('id'))
        print(request.POST.get('id'))
        deletedSwaps.delete()
        return HttpResponseRedirect(reverse('book_swap:show_processed_book_swap'))

# Processed Book Swap JSON
def get_processed_book_json(request):
    book_swap = BookSwap.objects.filter(swapped=False).filter(from_user=request.user.username)
    return HttpResponse(serializers.serialize("json", book_swap),
        content_type="application/json")
# Waiting Accept Book Swap JSON
def get_waiting_accept_book_json(request):
    book_swap = BookSwap.objects.exclude(from_user=request.user).filter(processed=False).filter(swapped=False)
    return HttpResponse(serializers.serialize("json", book_swap),
        content_type="application/json")
# Accepted Book Swap JSON
def get_accepted_book_json(request):
    book_swap = BookSwap.objects.filter(from_user=request.user).filter(swapped=False).filter(processed=True)
    return HttpResponse(serializers.serialize("json", book_swap),
        content_type="application/json")
# Finished Book Swap JSON
def get_finished_book_json(request):
    book_swap = BookSwap.objects.filter(from_user=request.user).filter(swapped=True)
    return HttpResponse(serializers.serialize("json", book_swap),
        content_type="application/json")

# Create Book Swap
@login_required
@csrf_exempt
def create_swap_mobile(request):
    if request.method == 'POST':
        ownedbook = request.POST.get('bookid')
        wantedbook = request.POST.get('bookid2')
        frommessage = request.POST.get('message')
        new_product = BookSwap.objects.create(
            from_user = request.user.username,
            have_book = ownedbook,
            from_message = frommessage,
            want_book = wantedbook,
        )
        new_product.save()
        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)
    
# Accept Book Swap
@login_required
@csrf_exempt
def cancel_swap_mobile(request):
    if request.method == 'POST':
        id = request.POST.get('id')
        book_swap = BookSwap.objects.filter(swapped=False).filter(from_user=request.user.username)
        book_swap.get(pk=id).delete()
        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)
    
# Accept Book Swap
@login_required
@csrf_exempt
def accept_swap_mobile(request):
    if request.method == 'POST':
        id = request.POST.get('id')
        book_swap = BookSwap.objects.exclude(from_user=request.user).filter(processed=False).filter(swapped=False)
        acceptedSwap = book_swap.get(pk=id)
        acceptedSwap.processed = True
        acceptedSwap.to_user = request.user.username
        acceptedSwap.to_message = request.POST.get('message')
        acceptedSwap.save()
        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

# Finish Book Swap
@login_required
@csrf_exempt
def finish_swap_mobile(request):
    if request.method == 'POST':
        id = request.POST.get('id')
        book_swap = BookSwap.objects.filter(from_user=request.user).filter(processed=True)
        acceptedSwap = book_swap.get(pk=id)
        acceptedSwap.swapped = True
        acceptedSwap.save()
        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core import serializers
from django.db.models import Q

from main.models import Book

# Create your views here.
def show_main(request):
    context = {
        'books': Book.objects.all(),
        'user': request.user,
        'n': range(5) # TODO: WILL BE REMOVED BEFORE PRODUCTION
    }
    return render(request, "main.html", context)

def get_books(request):
    data = Book.objects.all()
    return HttpResponse(
        serializers.serialize("json", data),
        content_type="application/json"
    )

def get_books_by_name(request, name):
    data = Book.objects.filter(Q(name__icontains=name) | Q(author__icontains=name))
    return HttpResponse(
        serializers.serialize("json", data),
        content_type="application/json"
    )

def get_books_by_genre(request, name):
    data = Book.objects.filter(Q(genre__icontains=name))
    return HttpResponse(
        serializers.serialize("json", data),
        content_type="application/json"
    )

# def get_books_by_id(request):
#     id_list = [int(x) for x in request.GET.get('id').split(',')]
#     data = Book.objects.filter(pk__in=id_list)
#     return HttpResponse(
#         serializers.serialize("json", data),
#         content_type="application/json"
#     )

book_swap/templates/accepted_swap.html
{% extends "book_swap_main.html" %}

{% block content2 %}
<div class="justify-center" id="mobile-content">
  <div class="text-center">
  <h1 class="font-bold text-3xl mx-3">Daftar Tukar Buku</h1>
  <div class="justify-center items-center inline-flex">
    <a href="{% url 'book_swap:show_processed_book_swap' %}">  
      <div class="text-white bg-gray-800 shadow rounded-lg my-3 p-2 mx-3" aria-current="page">
        <h1 class="font-bold">Diproses</h1>
      </div>
    </a>
    <a href="{% url 'book_swap:show_queue_book_swap' %}">  
      <div class="text-white bg-gray-800 hover:bg-gray-600 shadow rounded-lg my-3 p-2 mx-2">
        <h1 class="font-bold">Menunggu permintaan</h1>
      </div>
    </a>
    <a href="#">  
      <div class="text-white bg-gray-900 hover:bg-gray-600 shadow rounded-lg my-3 p-2 mx-3">
        <h1 class="font-bold">Diterima</h1>
      </div>
    </a>
  </div>

  <!--SearchBar-->
  <div class="md:inline-flex text-white bg-gray-800 shadow rounded-lg mx-3 my-3 p-6 justify-center items-center">
    <form action="{% url 'book_swap:show_queue_book_swap' %}">
      <button class="btn btn-outline-success hover:bg-blue-700 rounded" type="submit">Reset</button>
    </form>

    <h1 class="me-3">Cari kata kunci</h1>
    <form action="{% url 'book_swap:search_key' %}" method="POST">
      {% csrf_token %}
      <input
      class="form-control me-2 bg-gray-900"
      type="search"
      placeholder="Search"
      name="search_query"
      required aria-label="Search"
   >
    <button class="btn btn-outline-success hover:bg-blue-700 rounded" type="submit">Cari</button>
  </form>
  </div>
  <!--Card-->
  <div id="header">
    <div class="flex bg-gray-800 m-3 p-6">
      <div class="flex-auto w-32">
        <h1 class="font-semibold text-white text-center">Buku Kamu</h1>
      </div>
      <div class="flex-auto w-32">
        <h1 class="font-semibold text-white text-center">Buku Yang Diinginkan</h1>
      </div>
      <div class="flex-auto w-32">
        <h1 class="font-semibold text-white text-center">User Penerima</h1>
      </div>
      <div class="flex-auto w-32">
        <h1 class="font-semibold text-white text-center">Status</h1>
      </div>
      <div class="flex-auto w-32">
        <h1 class="font-semibold text-white text-center">Aksi</h1>
      </div>
    </div>
  </div>
  <!--<a href="{% url 'book_swap:delete_all_swap' %}">
    Reset
  </a>-->

  <div id="content" class="align-center p-3">
    <p>Tidak ada Konten</p>
  </div>
</div>

<script>
  async function getSwaps() {
        return fetch("{% url 'book_swap:get_accepted_book_json' %}").then((res) => res.json())
    }

  async function refreshSwaps(){
    document.getElementById("content").innerHTML = ""
    const swaps = await getSwaps()
    let content = ``
    swaps.forEach((swap) => {
      content += `
      <div class="flex bg-gray-800 m-3 p-6">
        <div class="flex-auto w-32">
        <h1 class="font-semibold text-white text-center">${swap.fields.have_book}</h1>
      </div>
      <div class="flex-auto w-32">
        <h1 class="font-semibold text-white text-center">${swap.fields.want_book}</h1>
      </div>
      <div class="flex-auto w-32">
        <h1 class="font-semibold text-white text-center">${swap.fields.from_user.name}</h1>
      </div>
      <div class="flex-auto w-32">
        <h1 class="font-semibold text-white text-center">${swap.fields.swapped}</h1>
      </div>
      <div class="flex-auto w-32">
        <a href="{% url 'book_swap:get_processed_book_json' %}">
          <button class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded">
            Selesaikan
          </button>
        </a>
      </div>
        </div>
      `
      document.getElementById("content").innerHTML = content
    })

  }
  refreshSwaps()
</script>
{% endblock %}

book_swap/templates/main.html
{% include "base.html" %}

{% block content %}
  {% block contents %}
  {% endblock %}
{% endblock %}

book_swap/templates/processed_book_swap.html
{% extends "book_swap_main.html" %}

{% block content2 %}
<!--Processed Book-->
<div class="justify-center" id="mobile-content">
  <div class="text-center">
  <h1 class="font-bold text-3xl mx-3">Daftar Tukar Buku</h1>
  <!--Option-->
  <div class="justify-center items-center inline-flex">
    <a href="#">  
      <div class="text-white bg-gray-900 shadow rounded-lg my-3 p-2 mx-3" aria-current="page">
        <h1 class="font-bold">Diproses</h1>
      </div>
    </a>
    <a href="{% url 'book_swap:show_queue_book_swap' %}">  
      <div class="text-white bg-gray-800 hover:bg-gray-600 shadow rounded-lg my-3 p-2 mx-2">
        <h1 class="font-bold">Menunggu permintaan</h1>
      </div>
    </a>
    <a href="{% url 'book_swap:show_accepted_book_swap' %}">  
      <div class="text-white bg-gray-800 hover:bg-gray-600 shadow rounded-lg my-3 p-2 mx-3">
        <h1 class="font-bold">Diterima</h1>
      </div>
    </a>
  </div>
  <!--SearchBar-->
  <div class="md:inline-flex text-white bg-gray-800 shadow rounded-lg mx-3 my-3 p-6 justify-center items-center">
    <a href="{% url 'book_swap:delete_all_swap' %}">
      Reset
    </a>
    <h1 class="me-3">Cari kata kunci</h1>
    <form action="{% url 'book_swap:search_key' %}" method="POST">
      {% csrf_token %}
      <input
      id="input"
      class="form-control me-2 bg-gray-900"
      type="search"
      placeholder="Search"
      name="search_query"
      required aria-label="Search"
   >
    <button id="search-button" class="btn btn-outline-success hover:bg-blue-700 rounded" type="submit">Cari</button>
  </form>
  </div>

  <!--Card-->
  <div id="header">
    <div class="flex bg-gray-800 m-3 p-6">
      <div class="flex-auto w-32">
        <h1 class="font-semibold text-white text-center">Buku Kamu</h1>
      </div>
      <div class="flex-auto w-32">
        <h1 class="font-semibold text-white text-center">Buku Yang Diminta</h1>
      </div>
      <div class="flex-auto w-32">
        <h1 class="font-semibold text-white text-center">User Penerima</h1>
      </div>
      <div class="flex-auto w-32">
        <h1 class="font-semibold text-white text-center">Status</h1>
      </div>
      <div class="flex-auto w-32">
        <h1 class="font-semibold text-white text-center">Aksi</h1>
      </div>
    </div>
  </div>



  <div id="content" class="align-center p-3">
    <p>Tidak ada Konten</p>
  </div>
</div>

<script>
  async function getSwaps() {
        return fetch("{% url 'book_swap:get_processed_book_json' %}").then((res) => res.json())
    }

  async function refreshSwaps(){
    document.getElementById("content").innerHTML = ""
    const swaps = await getSwaps()
    let content = ``
    swaps.forEach((swap) => {
      content += `
      <div class="flex bg-gray-800 m-3 p-6">
        <div class="flex-auto w-32">
        <h1 class="font-semibold text-white text-center">${swap.fields.want_book}</h1>
      </div>
      <div class="flex-auto w-32">
        <h1 class="font-semibold text-white text-center">${swap.fields.have_book}</h1>
      </div>
      <div class="flex-auto w-32">
        <h1 class="font-semibold text-white text-center">${
          swap.fields.to_user ? swap.fields.to_user : 'Tidak Ada'}</h1>
      </div>
      <div class="flex-auto w-32">
        <h1 class="font-semibold text-white text-center">${
          swap.fields.swapped 
            ? (swap.fields.processed === true ? 'Selesai' : 'Diproses') 
            : 'Belum ditukar'
        }</h1>
      </div>
      <div class="flex-auto w-32">
        <form method="POST">
          {% csrf_token %}
          <button class="text-white btn btn-outline-success hover:bg-blue-700 rounded" type="submit" onclick="cancelSwap(${swap.pk})">Batalkan</button>
        </form>
      </div>
        </div>
      `
      document.getElementById("content").innerHTML = content
    })

  }
  refreshSwaps()
  function cancelSwap(itemID) {
      fetch("{% url 'book_swap:cancel_swap' %}", {
            method: "POST",
            body: JSON.stringify({
              id: itemID,
            }),
        }).then(refreshProducts)

        document.getElementById("form").reset()
        return false
    }
</script>
{% endblock %}

book_swap/templates/request_swap.html
{% extends "request_swap_main.html" %}

{% block content1 %}
<!--Mobile Content-->
<div class="md" id="mobile-content">
  <!--Intro-->
  <div class="flex justify-center">
    <div class="overflow-x-auto text-white bg-gray-800 w-4/5 rounded-lg mx-5 my-3 p-6 justify-center">
        <h1>Request Buku yang Kamu Inginkan</h1>
        <form method="POST">
            {% csrf_token %}
            <h1>Nama Buku</h1>
            <div class="text-gray-900"> 
              {{ form.name }}
            </div>
            <h1>Pesan</h1>
            <div class="text-gray-900"> 
              {{ form.message }}
            </div>
          <input type="submit" value="Tukar Sekarang" class="bg-gray-900 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded h-8"/>
        </form>
      </div>
  </div>
  <!--Table-->
</div>

<style>
  #id_long_desc {
    width: 100px;
    height: 100px;
}
</style>
{% endblock %}

book_swap/templates/waiting_swap.html
{% extends "book_swap_main.html" %}

{% block content2 %}
<!--Mobile Content-->
<div class="justify-center" id="mobile-content">
  <!--Table-->
  <div class="text-center">
  <h1 class="font-bold text-3xl mx-3">Daftar Tukar Buku</h1>
  <div class="justify-center items-center inline-flex">
    <a href="{% url 'book_swap:show_processed_book_swap' %}">  
      <div class="text-white bg-gray-800 shadow rounded-lg my-3 p-2 mx-3" aria-current="page">
        <h1 class="font-bold">Diproses</h1>
      </div>
    </a>
    <a href="#">  
      <div class="text-white bg-gray-900 hover:bg-gray-600 shadow rounded-lg my-3 p-2 mx-2">
        <h1 class="font-bold">Menunggu permintaan</h1>
      </div>
    </a>
    <a href="{% url 'book_swap:show_accepted_book_swap' %}">  
      <div class="text-white bg-gray-800 hover:bg-gray-600 shadow rounded-lg my-3 p-2 mx-3">
        <h1 class="font-bold">Diterima</h1>
      </div>
    </a>
  </div>
  
  <div class="md:inline-flex text-white bg-gray-800 shadow rounded-lg mx-3 my-3 p-6 justify-center items-center">
    <form action="{% url 'book_swap:show_queue_book_swap' %}">
      <button class="btn btn-outline-success hover:bg-blue-700 rounded" type="submit">Reset</button>
    </form>

    <h1 class="me-3">Cari kata kunci</h1>
    <form action="{% url 'book_swap:search_key' %}" method="POST">
      {% csrf_token %}
      <input
      class="form-control me-2 bg-gray-900"
      type="search"
      placeholder="Search"
      name="search_query"
      required aria-label="Search"
   >
    <button class="btn btn-outline-success hover:bg-blue-700 rounded" type="submit">Cari</button>
  </form>
  </div>

  <!--Card-->
  <div id="header">
    <div class="flex bg-gray-800 m-3 p-6">
      <div class="flex-auto w-32">
        <h1 class="font-semibold text-white text-center">Buku Pengirim</h1>
      </div>
      <div class="flex-auto w-32">
        <h1 class="font-semibold text-white text-center">Buku Yang Diinginkan</h1>
      </div>
      <div class="flex-auto w-32">
        <h1 class="font-semibold text-white text-center">User Pengirim</h1>
      </div>
      <div class="flex-auto w-32">
        <h1 class="font-semibold text-white text-center">Aksi</h1>
      </div>
    </div>
  </div>
  <!--<a href="{% url 'book_swap:delete_all_swap' %}">
    Reset
  </a>-->

  <div id="content" class="align-center p-3">
    <p>Tidak ada Konten</p>
  </div>
</div>
<script>
  async function getSwaps() {
        return fetch("{% url 'book_swap:get_waiting_accept_book_json' %}").then((res) => res.json())
    }

  async function refreshSwaps(){
    document.getElementById("content").innerHTML = ""
    const swaps = await getSwaps()
    let content = ``
    swaps.forEach((swap) => {
      content += `
      <div class="flex bg-gray-800 m-3 p-6">
        <div class="flex-auto w-32">
        <h1 class="font-semibold text-white text-center">${swap.fields.want_book}</h1>
      </div>
      <div class="flex-auto w-32">
        <h1 class="font-semibold text-white text-center">${swap.fields.have_book}</h1>
      </div>
      <div class="flex-auto w-32">
        <h1 class="font-semibold text-white text-center">${swap.fields.from_user}</h1>
      </div>
      <div class="flex-auto w-32">
        <a href="">
          <button class="bg-red-500 hover:bg-red-700 text-white font-bold py-2 px-4 rounded" onclick=acceptReq(${swap.pk})>
            Terima
          </button>
        </a>
      </div>
        </div>
      `
      document.getElementById("content").innerHTML = content
    })
  }
  refreshSwaps()
  function acceptReq(id){
    fetch("{% url 'book_swap:accept_book_swap' %}", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "X-CSRFToken": "{{ csrf_token }}"
      },
      body: JSON.stringify({id: id})
    }).then(() => {
      refreshSwaps()
    })
  }
</script>
{% endblock %}