book_catalogue/urls.py
from django.contrib import admin
from django.urls import path, include
from book_catalogue import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('users.urls')),
    path('', include('book_swap.urls')),
    path('', include('book_request.urls')),
    path('', include('user_profile.urls')),
    path('', include('catalog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

book_request/urls.py
from django.urls import path
from book_request.views import request_book_by_ajax, get_requested_book_json, view_all_requests, approve_request, reject_request, request_book_mobile

app_name = 'book_request'

urlpatterns = [
    path('request-book/', request_book_by_ajax, name='request_book'),
    path('get-requested-book/', get_requested_book_json, name='get_requested_book'),
    path('requests/', view_all_requests, name='view_all_requests'),
    path('requests/approve/<int:request_id>', approve_request, name='approve_request'),
    path('requests/reject/<int:request_id>', reject_request, name='reject_request'),
    path('request-book-mobile/', request_book_by_ajax, name='request_book_mobile'),
]

book_swap/urls.py
from django.urls import path
from book_swap.views import show_json, show_processed_book_swap, show_queue_book_swap
from book_swap.views import show_accepted_book_swap, accept_swap,get_processed_book_json, search_key
from book_swap.views import cancel_swap
from book_swap.views import create_swap_mobile, create_swap, show_create_swap
from book_swap.views import get_model_data, delete_all_swap
from book_swap.views import get_processed_book_json, get_waiting_accept_book_json, get_accepted_book_json, get_finished_book_json
from book_swap.views import cancel_swap_mobile, accept_swap_mobile, finish_swap_mobile
app_name = 'book_swap'

urlpatterns = [
    path('delete_all_swap/', delete_all_swap, name='delete_all_swap'),
    path('get_model_data/', get_model_data, name='get_model_data'),
    path('create_swap/', create_swap, name='create_swap'),
    path('create_swap_page/', show_create_swap, name='show_create_swap'),
    path('waiting_swap/', show_queue_book_swap, name='show_queue_book_swap'), 
    path('book_swap/', show_processed_book_swap, name='show_processed_book_swap'),
    path('accepted_swap/', show_accepted_book_swap, name='show_accepted_book_swap'), 
    path('book_swap/json/', show_json, name='show_json'),
    path('book_swap/search/', search_key, name='search_key'),
    path('accept_swap/', accept_swap, name='accept_swap'),
    path('cancel_swap/', cancel_swap, name='cancel_swap'),
    path('get_processed_book_json/', get_processed_book_json, name='get_processed_book_json'),
    path('get_waiting_accept_book_json/', get_waiting_accept_book_json, name='get_waiting_accept_book_json'),
    path('get_accepted_book_json/', get_accepted_book_json, name='get_accepted_book_json'),
    path('get_finished_book_json/', get_finished_book_json, name='get_finished_book_json'),
    path('create_swap_mobile/', create_swap_mobile, name='create_swap_mobile'),
    path('cancel_swap_mobile/', cancel_swap_mobile, name='cancel_swap_mobile'),
    path('accept_swap_mobile/', accept_swap_mobile, name='accept_swap_mobile'),
    path('finish_swap_mobile/', finish_swap_mobile, name='finish_swap_mobile'),
]

main/urls.py
from django.urls import path
from main.views import get_books, get_books_by_genre, get_books_by_name, show_main

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('get-books/', get_books, name='get_books'),
    path('get-books-by-name/<str:name>', get_books_by_name, name='get_books_by_name'),
    path('get-books-by-genre/<str:name>', get_books_by_genre, name='get_books_by_genre'),
]

user_profile/urls.py
from django.urls import path
from .views import *


app_name = 'user_profile'

urlpatterns = [
    path('profile/<int:pk>', view_profile_byId, name='view_profile'),
    path('profile/', view_self_profile, name='view_myprofile'),
    path('profile/edit/', edit_profile, name='edit_profile'),
    path('add-favorite/', add_favorite, name='add_favorite'),
    path('get_buku_by_id/<int:id>/', get_buku_by_id, name='get_buku_by_id'),

    path('user/<int:user_id>/', get_username_by_id, name='get_username_by_id'),
    path('profileflutter/', get_profile_flutter, name='view_flutter'),
    path('editprofile-mobile/', edit_profile_mobile, name='edit_profile_flutter'),
    path('fav-mobile/<int:favchange>', edit_fav_mobile, name='fav-mobile'),

    

]

users/urls.py
from django.urls import path

from users.views import login_user, login_user_mobile, logout_user, logout_user_mobile, register_user, register_user_mobile

app_name = 'users'

urlpatterns = [
    path('login/', login_user, name='login'),
    path('register/', register_user, name='register'),
    path('logout/', logout_user, name='logout'),
    path('login-mobile/', login_user_mobile, name='login-mobile'),
    path('register-mobile/', register_user_mobile, name='register-mobile'),
    path('logout-mobile/', logout_user_mobile, name='logout-mobile'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0"
        />
        
        <link href='https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900' rel='stylesheet'>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="{% static 'styles/global.css' %}">
        
        <!-- <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.0.0/flowbite.min.css" rel="stylesheet" /> -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.0.0/flowbite.min.js"></script>
        
        <!-- Uncomment this line below if want to enable Tailwind -->
        <script src="https://cdn.tailwindcss.com"></script>
        
        <!-- Uncomment this line below if want to enable Bootstrap -->
        <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous"> -->
        
        <!-- Uncomment this line below if want to enable Popperjs -->
        <!-- <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script> -->
        
        <!-- Uncomment this line below if want to enable JQuery -->
        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha384-KyZXEAg3QhqLMpG8r+J4jsl5c9zdLKaUk5Ae5f5b1bw6AUn5f5v8FZJoMxm6f5cH1" crossorigin="anonymous"></script>
        
        {% block meta %}
        {% endblock meta %}
    </head>

    <body class="min-h-screen">
        {% block content %}
        {% endblock content %}
    </body>
</html>

templates/header.html
<!-- Header -->
<div class="flex flex-row h-[60px] lg:mb-[25px] border py-3 px-5 justify-between items-center">
    <div class="flex flex-row w-[300px] justify-self-start items-center gap-2">
        <div id="dropdown_general_button" class="lg:hidden mouse-pointer" onclick="toggleDropdownGeneral()">
            <svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 448 512">
                <path d="M16 132h416c8.837 0 16-7.163 16-16V76c0-8.837-7.163-16-16-16H16C7.163 60 0 67.163 0 76v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16z"/>
            </svg>
        </div>
        <h1 class="font-bold text-xl">BookPals</h1>
    </div>
    <div>
        <ul class="lg:flex flex-row gap-16 hidden">
            <li class="text-gray-800 font-semibold"><a href="{% url 'main:show_main' %}">Home</a></li>
            <li class="text-gray-800 font-semibold"><a href="{% url 'book_request:request_book' %}">Add New Book</a></li>
            <li class="text-gray-800 font-semibold"><a href="https://github.com/D09-PBP2023/proyek-tengah/blob/main/README.md">About Us</a></li>
        </ul>
    </div>
    <div class="flex flex-row gap-4 relative w-[300px] items-end justify-end">
        {% if user.is_authenticated %}
            <div class="flex flex-col mx-5">
                <button id="dropdown_user_button" class="flex flex-row items-center justify-center gap-2" onclick="toggleDropdownUser()">
                    <h1 class="font-semibold">{{ user.username }}</h1>
                    <svg class="h-5 w-5 text-gray-800" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"
                        fill="currentColor"><path fill-rule="evenodd"
                            d="M5.293 7.293a1 1 0 011.414 0L10
                            10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                            clip-rule="evenodd" /></svg>
                </button>
                <div id="dropdown_user_menu" class="flex flex-col origin-top-right opacity-0 transition scale-0 divide-y absolute z-20 top-[50px] right-[20px] w-[200px] border rounded-lg bg-white shadow-md">
                    <a href="{% url 'user_profile:view_myprofile' %}" class="flex justify-end px-4 py-2 cursor-pointer hover:bg-gray-200">
                        Profile
                    </a>
                    <a href="{% url 'book_swap:show_processed_book_swap' %}" class="flex justify-end px-4 py-2 cursor-pointer hover:bg-gray-200">
                        Requests
                    </a>
                    <a href="{% url 'users:logout' %}" class="flex justify-end px-4 py-2 cursor-pointer hover:bg-gray-200">
                        Sign Out
                    </a>
                </div>
            </div>
        {% else %}
            <a href="{% url 'users:login' %}" class="px-3 py-2">Login</a>
            <a href="{% url 'users:register' %}" class="px-8 py-2 border rounded-xl bg-sky-500 text-white">Sign Up</a>
        {% endif %}
    </div>
</div>
<!-- Subheader for Mobile -->
<div id="dropdown_general_menu" class="flex flex-col h-0 origin-top w-full transition scale-0 divide-y mb-[25px] lg:hidden border py-3 justify-between items-center">
    <a href="{% url 'main:show_main' %}" class="flex justify-center w-full px-4 py-2 cursor-pointer hover:bg-gray-200">
        Home
    </a>
    <a href="{% url 'book_request:request_book' %}" class="flex justify-center w-full px-4 py-2 cursor-pointer hover:bg-gray-200">
        Add New Book
    </a>
    <a href="{% url 'users:logout' %}" class="flex justify-center w-full px-4 py-2 cursor-pointer hover:bg-gray-200">
        About Us
    </a>
</div>