book_catalogue/urls.py
from django.contrib import admin
from django.urls import path, include
from book_catalogue import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('users.urls')),
    path('', include('book_swap.urls')),
    path('', include('book_request.urls')),
    path('', include('user_profile.urls')),
    path('', include('catalog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/urls.py
from django.urls import path
from catalog.views import book_details, bookmark_book, bookmark_book_flutter, get_marked_books, get_review, add_review, get_average_rating, create_review_flutter
from user_profile.views import view_bookmarked_list

app_name = 'catalog'

urlpatterns = [
    path('book_details/<int:id>/', book_details, name='book_details'),
    # path('book/<int:id>/', book, name='book'),
    path('bookmark_book/<int:id>/', bookmark_book, name='bookmark_book'),
    path('bookmarked/', view_bookmarked_list, name='view_bookmarked_list'),
    path('get_marked_books/', get_marked_books, name='get_marked_books'),
    path('get_review/<int:id>/', get_review, name='get_review'),
    path('add_review/<int:id>/', add_review, name='add_review'),
    path('get_average_rating/<int:id>/', get_average_rating, name='get_average_rating'),
    path('add-review-flutter/', create_review_flutter, name='create_review_flutter'),
    path('bookmarkflutter/<int:id>/', bookmark_book_flutter, name='bookmark_book_flutter'),
]

main/urls.py
from django.urls import path
from main.views import get_books, get_books_by_genre, get_books_by_name, show_main

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('get-books/', get_books, name='get_books'),
    path('get-books-by-name/<str:name>', get_books_by_name, name='get_books_by_name'),
    path('get-books-by-genre/<str:name>', get_books_by_genre, name='get_books_by_genre'),
]

users/urls.py
from django.urls import path

from users.views import login_user, login_user_mobile, logout_user, logout_user_mobile, register_user, register_user_mobile

app_name = 'users'

urlpatterns = [
    path('login/', login_user, name='login'),
    path('register/', register_user, name='register'),
    path('logout/', logout_user, name='logout'),
    path('login-mobile/', login_user_mobile, name='login-mobile'),
    path('register-mobile/', register_user_mobile, name='register-mobile'),
    path('logout-mobile/', logout_user_mobile, name='logout-mobile'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Avg

class Book(models.Model):
    name = models.CharField(max_length=512)
    author = models.CharField(max_length=512)
    original_language = models.CharField(max_length=256)
    year_published = models.IntegerField()
    sales = models.IntegerField()
    genre = models.CharField(max_length=256)
    cover_image = models.ImageField(null=True, upload_to="input/cover")

    @property
    def calculate_average_rating(self):
        return Review.objects.filter(book=self).aggregate(avg_rating=Avg('rating'))['avg_rating']

class Review(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    review = models.TextField(max_length=512)
    rating = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)

main/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core import serializers
from django.db.models import Q

from main.models import Book

# Create your views here.
def show_main(request):
    context = {
        'books': Book.objects.all(),
        'user': request.user,
        'n': range(5) # TODO: WILL BE REMOVED BEFORE PRODUCTION
    }
    return render(request, "main.html", context)

def get_books(request):
    data = Book.objects.all()
    return HttpResponse(
        serializers.serialize("json", data),
        content_type="application/json"
    )

def get_books_by_name(request, name):
    data = Book.objects.filter(Q(name__icontains=name) | Q(author__icontains=name))
    return HttpResponse(
        serializers.serialize("json", data),
        content_type="application/json"
    )

def get_books_by_genre(request, name):
    data = Book.objects.filter(Q(genre__icontains=name))
    return HttpResponse(
        serializers.serialize("json", data),
        content_type="application/json"
    )

# def get_books_by_id(request):
#     id_list = [int(x) for x in request.GET.get('id').split(',')]
#     data = Book.objects.filter(pk__in=id_list)
#     return HttpResponse(
#         serializers.serialize("json", data),
#         content_type="application/json"
#     )

main/templates/header.html
<!-- Header -->
<div class="flex flex-row h-[60px] lg:mb-[25px] border py-3 px-5 justify-between items-center">
    <div class="flex flex-row w-[300px] justify-self-start items-center gap-2">
        <div id="dropdown_general_button" class="lg:hidden mouse-pointer" onclick="toggleDropdownGeneral()">
            <svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 448 512">
                <path d="M16 132h416c8.837 0 16-7.163 16-16V76c0-8.837-7.163-16-16-16H16C7.163 60 0 67.163 0 76v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16zm0 160h416c8.837 0 16-7.163 16-16v-40c0-8.837-7.163-16-16-16H16c-8.837 0-16 7.163-16 16v40c0 8.837 7.163 16 16 16z"/>
            </svg>
        </div>
        <h1 class="font-bold text-xl">BookPals</h1>
    </div>
    <div>
        <ul class="lg:flex flex-row gap-16 hidden">
            <li class="text-gray-800 font-semibold"><a href="{% url 'main:show_main' %}">Home</a></li>
            <li class="text-gray-800 font-semibold"><a href="#">Add New Book</a></li>
            <li class="text-gray-800 font-semibold"><a href="#">About Us</a></li>
        </ul>
    </div>
    <div class="flex flex-row gap-4 relative w-[300px] items-end justify-end">
        {% if user.is_authenticated %}
            <div class="flex flex-col mx-5">
                <button id="dropdown_user_button" class="flex flex-row items-center justify-center gap-2" onclick="toggleDropdownUser()">
                    <h1 class="font-semibold">{{ user.username }}</h1>
                    <svg class="h-5 w-5 text-gray-800" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"
                        fill="currentColor"><path fill-rule="evenodd"
                            d="M5.293 7.293a1 1 0 011.414 0L10
                            10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z"
                            clip-rule="evenodd" /></svg>
                </button>
                <div id="dropdown_user_menu" class="flex flex-col origin-top-right opacity-0 transition scale-0 divide-y absolute z-20 top-[50px] right-[20px] w-[200px] border rounded-lg bg-white shadow-md">
                    <a href="#" class="flex justify-end px-4 py-2 cursor-pointer hover:bg-gray-200">
                        Profile
                    </a>
                    <a href="#" class="flex justify-end px-4 py-2 cursor-pointer hover:bg-gray-200">
                        Requests
                    </a>
                    <a href="{% url 'users:logout' %}" class="flex justify-end px-4 py-2 cursor-pointer hover:bg-gray-200">
                        Sign Out
                    </a>
                </div>
            </div>
        {% else %}
            <a href="{% url 'users:login' %}" class="px-3 py-2">Login</a>
            <a href="{% url 'users:register' %}" class="px-8 py-2 border rounded-xl bg-sky-500 text-white">Sign Up</a>
        {% endif %}
    </div>
</div>
<!-- Subheader for Mobile -->
<div id="dropdown_general_menu" class="flex flex-col h-0 origin-top w-full transition scale-0 divide-y mb-[25px] lg:hidden border py-3 justify-between items-center">
    <a href="{% url 'main:show_main' %}" class="flex justify-center w-full px-4 py-2 cursor-pointer hover:bg-gray-200">
        Home
    </a>
    <a href="#" class="flex justify-center w-full px-4 py-2 cursor-pointer hover:bg-gray-200">
        Add New Book
    </a>
    <a href="{% url 'users:logout' %}" class="flex justify-center w-full px-4 py-2 cursor-pointer hover:bg-gray-200">
        About Us
    </a>
</div>

main/templates/main.html
{% extends 'base.html' %} 

{% block content %}

<div>
    <!-- Header -->
    {% include 'header.html' %}
    <!-- Featured books -->
    <div>
        <h1 class="font-bold text-3xl mx-[50px] my-[20px]">For You</h1>
        <div class="flex justify-center items-center">
            <div id="featured_books" class="flex flex-col lg:flex-row w-full h-auto lg:h-[250px] items-center gap-3 overflow-x-auto snap-x snap-normal snap-mandatory">
                <!-- Coded in javascript -->
            </div>
        </div>
    </div>
    <!-- Browse books -->
    <div class="flex flex-col mt-[30px] mb-[60px]">
        <h1 class="font-bold text-2xl mx-[50px]">Browse</h1>
        <div class="flex flex-col justify-center items-center my-5 gap-1">
            <h1 class="font-bold text-lg">Search your books here!</h1>
            <input id="search_input" type="text" class="rounded-xl bg-gray-200 w-[300px] lg:w-[350px] h-[40px] px-3 py-1 border-black border" placeholder="The title..." value="" autocomplete="off">
        </div>
        <div id="browse_books" class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 2xl:grid-cols-4 w-full h-auto items-center justify-center justify-items-center gap-4 px-[50px] py-2">
            <!-- Coded in javascript -->
        </div>
    </div>
</div>

<script>
    const featured_book_ids = [3, 7, 6, 68, 32];
    const featured_book_colors = {
        3: 'from-indigo-800 to-indigo-400', 
        6: 'from-red-600 to-red-300', 
        7: 'from-sky-500 to-sky-200',
        68: 'from-green-700 to-green-500',
        32: 'from-pink-400 to-pink-200',
    };

    async function getBooks() {
        return fetch("{% url 'main:get_books' %}").then((res) => res.json());
    }

    async function getAverageRating(id) {
        var url_mask = "{% url 'catalog:get_average_rating' id=170013 %}".replace(/170013/, id.toString());
        return fetch(url_mask).then((res) => res.json());
    }

    async function buildFeaturedBooks(featured_books) {
        document.getElementById("featured_books").innerHTML = "";
        let htmlString = ``;
        featured_books.forEach(async (book) => {
            let rating = await getAverageRating(book.pk)
            htmlString += `\n
            <a href="{% url 'catalog:book_details' id=177013 %}">
                <div class="flex flex-row relative snap-center items-center hover:cursor-pointer rounded-xl transition shadow-md hover:shadow-xl w-[300px] lg:w-[400px] h-[200px] px-4 py-3 mx-1 gap-3 bg-gradient-to-t ${featured_book_colors[book.pk]}">
                    <img src='media/${book.fields.cover_image}' class='w-[100px] rounded-lg drop-shadow-md'>
                    <div class="flex-col w-[200px] lg:w-[300px]">
                        <div class="line-clamp-1 lg:line-clamp-2 font-bold text-md lg:text-lg text-white">${book.fields.name}</div>
                        <div class="line-clamp-1 text-white">By ${book.fields.author}</div>
                        <div class="h-[5px]"></div>
                        <div class="truncate text-white text-xs">${book.fields.genre}</div>
                        <div class="truncate text-white text-xs">${book.fields.original_language} - ${book.fields.year_published}</div>
                        <div class="flex flex-row gap-2">
                            ${getStarRatingHtml(rating.average_rating)}
                        </div>
                    </div>
                </div>
            </a>`.replaceAll('177013', book.pk)
            document.getElementById("featured_books").innerHTML = htmlString;
        });
        
    }

    async function buildBrowseBooks(books) {
        document.getElementById("browse_books").innerHTML = "";
        let htmlString = ``;
        books.forEach(async (book) => {
            let rating = await getAverageRating(book.pk)
            htmlString += `\n
            <a href="{% url 'catalog:book_details' id=177013 %}">
                <div class="flex flex-row items-center rounded-xl border transition shadow-md hover:shadow-xl w-[350px] sm:w-[250px] lg:w-[350px] h-[200px] px-4 py-3 gap-3 cursor-pointer">
                    <img src='media/${book.fields.cover_image}' class='w-[100px] rounded-lg drop-shadow-md'>
                    <div class="flex-col w-[250px] sm:w-[150px] lg:w-[250px]">
                        <div class="line-clamp-1 lg:line-clamp-2 font-semibold text-lg text-black">${book.fields.name}</div>
                        <div class="line-clamp-1 font-normal text-slate-400 text-sm">${book.fields.author}</div>
                        <div class="flex flex-row gap-2">
                            ${getStarRatingHtml(rating.average_rating)}
                        </div>
                    </div>
                </div>
            </a>`.replaceAll('177013', book.pk)
            document.getElementById("browse_books").innerHTML = htmlString;
        });
        

        const hiddenElements = document.querySelectorAll("#card-book");
        hiddenElements.forEach((element) => booksCardObserver.observe(element));
    }

    function getStarRatingHtml(rating) {
        const maxRating = 5;
        let starHtml = '';
        if (rating === null || rating === undefined) {
            rating = 0;
        }
        console.debug(rating);
        starHtml += '<div class="flex items-center">';
        for (let i = 1; i <= maxRating; i++) {
            if (i <= rating) {
                starHtml += '<svg class="w-4 h-4 text-yellow-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20"><path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"></path></svg>';
            } else {
                starHtml += '<svg class="w-4 h-4 text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 22 20"><path d="M20.924 7.625a1.523 1.523 0 0 0-1.238-1.044l-5.051-.734-2.259-4.577a1.534 1.534 0 0 0-2.752 0L7.365 5.847l-5.051.734A1.535 1.535 0 0 0 1.463 9.2l3.656 3.563-.863 5.031a1.532 1.532 0 0 0 2.226 1.616L11 17.033l4.518 2.375a1.534 1.534 0 0 0 2.226-1.617l-.863-5.03L20.537 9.2a1.523 1.523 0 0 0 .387-1.575Z"></path></svg>';
            }
        }
        starHtml += '</div>';

        return starHtml;
    }

    async function refreshBooks() {
        const books = await getBooks();
        const featured_books = books.filter(book => featured_book_ids.includes(book.pk));
        
        buildFeaturedBooks(featured_books);
        buildBrowseBooks(books);
    }

    function toggleDropdownUser() {
        const dropdownButton = document.getElementById("dropdown_user_button");
        const dropdownMenu = document.getElementById("dropdown_user_menu");
        
        dropdownMenu.classList.toggle('opacity-0');
        dropdownMenu.classList.toggle('scale-100');
        dropdownMenu.classList.toggle('scale-0');
    }

    function toggleDropdownGeneral() {
        const dropdownButton = document.getElementById("dropdown_general_button");
        const dropdownMenu = document.getElementById("dropdown_general_menu");

        dropdownMenu.classList.toggle('scale-100');
        dropdownMenu.classList.toggle('scale-0');
        dropdownMenu.classList.toggle('h-0');
    }
    
    let lastTime = -1;
    function searchBooks(value, searchTime) {
        lastTime = searchTime;
        setTimeout(async function() { // Make sure not to spam request to backend
            if (searchTime != lastTime) return;
            if (value && value != "") {
                const books = await fetch(`{% url 'main:get_books_by_name' 177013 %}`.replace('177013', value)).then((res) => res.json());
                buildBrowseBooks(books);
            } else {
                buildBrowseBooks(await getBooks());
            }
        }, 700);
    }

    const booksCardObserver = new IntersectionObserver((entries) => {
        entries.forEach((entry) => {
            if (entry.isIntersecting) {
                entry.target.classList.remove('opacity-0');
                entry.target.classList.remove('blur-md');
                entry.target.classList.remove('translate-y-full');
                entry.target.classList.add('opacity-1');
                entry.target.classList.add('blur-none');
                entry.target.classList.add('translate-y-0');
            }
        });
    });

    const searchInput = document.getElementById("search_input");

    refreshBooks();
    searchInput.oninput = function(event) {
        searchBooks(event.target.value, event.timeStamp);
    };
</script>
{% endblock %}